input_path: "input.xlsx"
new_column_name: "业务类型"
sheet_names:
  - "Sheet1"
  - "Sheet2"
columns_to_check_map:
  Column1:
    "整车": "整车业务"
    "二手车": "二手车业务"
    "旧车": "二手车业务"
    "维修": "维修业务"
  Column2:
    "新车": "新车业务"
    "租车": "租车业务"
    "保养": "保养业务"
output_path: "output.xlsx"
